#!/usr/bin/python3

import socket
import time
import struct
import atexit
import signal
import sys
import select
import tty
import termios

import click


@click.command()
@click.option('--ip', default="127.0.0.1", help='ip to send packets')
@click.option('--port', default=5602, help='udp port')
@click.option('--pksize', default=1024, help='packet size')
@click.option('--pks', default=800, help='bitrate in pkt/s')
@click.option('--lid', default=1, help='link id')
def main(lid,ip, port,pksize,pks):
    
    sock = None
    
    def cleanup():
        try:
            if sock is not None:
                sock.close()
        except Exception as e:
            print(e)
                
    def signal_handler(sig, frame):
        cleanup()
        sys.exit(0)
        
    atexit.register(cleanup)
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    #------------------------------------------------------------------
    UDP_IP = ip
    UDP_PORT = port
    PACKET_SIZE = pksize
    BITRATE = pks  # packets/sec
    link_id = lid
    BASE_DELAY=1/BITRATE
    #------------------------------------------------------------------
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1) 
    remaining_bytes = b"\xFF" * (PACKET_SIZE - 4 - 4 - 8)

    time_ls= time.time()
    time_start= time.time()    
    i=0

                
    while True:
        i+=1
        packet_number = i
        packet_time = time.time()
        packet = struct.pack("!IId"+str((PACKET_SIZE - 4 - 4 - 8))+"s", link_id, packet_number, packet_time,remaining_bytes)
        delay_usec=BASE_DELAY-(time.time()-time_ls)
        if delay_usec < 0:
            delay_usec=0
        time.sleep(delay_usec)
                
        sock.sendto(packet, (UDP_IP, UDP_PORT))
        time_ls=time.time() 
            
if __name__ == '__main__':
    main()
